version: '3.8'

services:
  app:
    build: .
    container_name: symfony_app
    volumes:
      - .:/var/www/html:delegated
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=your_access_key
      - AWS_SECRET_ACCESS_KEY=your_secret_key
      - AWS_DEFAULT_REGION=your_region
    command: symfony serve --port=8000

  db:
    image: mysql:5.7
    container_name: symfony_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=symfony
      - MYSQL_PASSWORD=symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local
